### ISSUE TITLE
Picture stops while playing a video

### ISSUE THREAD

**Issue by drieschel** [surkovalex/OpenELEC.tv#11]
While playing a video, sometimes the picture stops but the sound is still playing. 

This happens with any version of branch openelec-6.0 compiled for S82 (of course on a S82).

_If this description is not precisely enough, I can still try to write it more detailed._

**Edit:** Is this problem S82 specific or have other devices the same problem?

**Comment by surkovalex** [comment]
So far, no one complained about a similar problem. Need more information and details.

**Comment by drieschel** [comment]
This persons seem to have the same problem:
http://xbmc.ru/forum/showpost.php?p=79396&postcount=1503
http://xbmc.ru/forum/showpost.php?p=84156&postcount=1827

**Comment by drieschel** [comment]
@surkovalex Is the frame buffer fix for solving this problem?

**Comment by surkovalex** [comment]
I try, but I can not repeat the problem.

**Comment by drieschel** [comment]
My question was related to the fb patches you added in the commits 702b253c22950bea17cc4d2fa990c864a0bae4ea and 57e69a0d366a2cbee0666da30736379489096616.
