### ISSUE TITLE
How can I add WiFi modules for RTL8189 WiFi chip for MXQ

### ISSUE THREAD

**Issue by pigbait** [surkovalex/OpenELEC.tv#13]
Hello was wondering how I could add WiFi modules for RTL8189 WiFi chip on MXQ I've tried compiling MXQ build by changing wifidummy to 8189es but that hasn't worked

Thanks for the help

**Comment by surkovalex** [comment]
Change in linux.arm.conf 
# CONFIG_RTL8189ES is not set to CONFIG_RTL8189ES=m
and try again

**Comment by pigbait** [comment]
Awesome I'll give that a try

**Comment by pigbait** [comment]
make[1]: Entering directory '/home/pigabit/Documents/OpenELEC.tv/build.OpenELEC-Amlogic.MXQ.arm-devel/linux-amlogic-3.10-6cd008d'
  CHK     include/generated/uapi/linux/version.h
  CHK     include/generated/utsrelease.h
  CC      scripts/mod/devicetable-offsets.s
make[2]: 'include/generated/mach-types.h' is up to date.
  CALL    scripts/checksyscalls.sh
  GEN     scripts/mod/devicetable-offsets.h
  HOSTCC  scripts/mod/file2alias.o
  HOSTLD  scripts/mod/modpost
  Building modules, stage 2.
  MODPOST 99 modules
ERROR: "aml_gsl_clear_api" [drivers/amlogic/touch/gsl_point_id.ko] undefined!
ERROR: "aml_gsl_get_api" [drivers/amlogic/touch/gsl_point_id.ko] undefined!
ERROR: "aml_gsl_register_api" [drivers/amlogic/touch/gsl_point_id.ko] undefined!
/home/pigabit/Documents/OpenELEC.tv/build.OpenELEC-Amlogic.MXQ.arm-devel/linux-amlogic-3.10-6cd008d/scripts/Makefile.modpost:88: recipe for target '__modpost' failed
make[2]: *** [__modpost] Error 1
Makefile:968: recipe for target 'modules' failed
make[1]: *** [modules] Error 2
make[1]: Leaving directory '/home/pigabit/Documents/OpenELEC.tv/build.OpenELEC-Amlogic.MXQ.arm-devel/linux-amlogic-3.10-6cd008d'
make: *** [release] Error 2


this is the errors i get when i build with that modification

**Comment by surkovalex** [comment]
Set CONFIG_AML_TOUCH_ALGORITHM_SUPPORT to "# CONFIG_AML_TOUCH_ALGORITHM_SUPPORT is not set"

**Comment by pigbait** [comment]
Thanks for the tips, got it working thanks so much for your help.
