### ISSUE TITLE
patch fails

### ISSUE THREAD

**Issue by JustMev** [surkovalex/OpenELEC.tv#15]
APPLY PATCH (project)   /home/jMe/OpenELEC.tv/projects/Amlogic/patches/kodi/0015-aml-Add-some-key-mappings-for-HDMI-CEC.patch
patching file xbmc/input/linux/LinuxInputDevices.cpp
Hunk #1 FAILED at 250.
1 out of 1 hunk FAILED -- saving rejects to file xbmc/input/linux/LinuxInputDevices.cpp.rej

**Comment by surkovalex** [comment]
Hi.Yes, I know, I have not yet fixed.

**Comment by surkovalex** [comment]
Fixed https://github.com/surkovalex/OpenELEC.tv/commit/59ed47752c1ddebf59982924d3b21a6576278237
