### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by assafla** [surkovalex/OpenELEC.tv#19]
LD [M] drivers/amlogic/wifi/realtek/rtl8xxx_EU/8188eu.o
Makefile:817: recipe for target drivers failed
make[1]: *** [drivers] Error 2

it is inside linux-amlogic-3.10-7a3.... make

**Comment by assafla** [comment]
it is during LD link

**Comment by assafla** [comment]
its on the openelec-6.0
project x8hp amlogic

**Comment by surkovalex** [comment]
I have compiled without error
http://pastebin.com/EFGPAnYC
670 string

**Comment by assafla** [comment]
I'll try a fresh build.

**Comment by assafla** [comment]
are you using a 32bit ubuntu machine? or 64Bit?

**Comment by surkovalex** [comment]
I use Debian 64bit

**Comment by assafla** [comment]
i get gap/mpc/mpfr missing in gcc build' although they are there....do you have any idea?

**Comment by assafla** [comment]
did a fresh install solved it for me. Tx
