### ISSUE TITLE
Skipping patch.

### ISSUE THREAD

**Issue by JustMev** [surkovalex/OpenELEC.tv#20]
APPLY PATCH (project)   /home/deb/OpenELEC.tv/projects/Amlogic/devices/M8/patches/linux/m8.patch
patching file arch/arm/boot/dts/amlogic/meson8_k200a_2G.dtd
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.
1 out of 1 hunk ignored -- saving rejects to file arch/arm/boot/dts/amlogic/meson8_k200a_2G.dtd.rej

**Comment by surkovalex** [comment]
Thank you. Fixed.

**Comment by VDRrulez** [comment]
Yes, you have fixed it. But there are other devices too.
APPLY PATCH (project)   /root/OpenELEC.tv/projects/Amlogic/devices/S82/patches/linux/linux-s82_dtd.patch
patching file arch/arm/boot/dts/amlogic/meson8_k200b_1G_emmc_sdhc.dtd
Reversed (or previously applied) patch detected!  Assume -R? [n] 
Apply anyway? [n] 
Skipping patch.

**Comment by drieschel** [comment]
I have the same problem with S82.

**Comment by surkovalex** [comment]
I have no errors.
      APPLY PATCH (project)   /build/OpenELEC.tv/projects/Amlogic/devices/S82/patches/linux/linux-s82_dtd.patch
patching file arch/arm/boot/dts/amlogic/meson8_k200b_1G_emmc_sdhc.dtd
patching file arch/arm/boot/dts/amlogic/meson8_k200b_1G_emmc_sdio.dtd
patching file arch/arm/boot/dts/amlogic/meson8_k200b_2G_emmc_sdhc.dtd
patching file arch/arm/boot/dts/amlogic/meson8_k200b_2G_emmc_sdio.dtd
patching file arch/arm/boot/dts/amlogic/meson8m2_n200_1G.dtd
patching file arch/arm/boot/dts/amlogic/meson8m2_n200_2G.dtd

**Comment by drieschel** [comment]
Which patches should I apply and which not? Why is it asking everytime? Can you show me the command line you are using for calling make?

**Comment by VDRrulez** [comment]
@drieschel  
Update your repository (git pull) and kernel will compile with no errors.
@surkovalex 
Thanks for the fix. Keep up the good work!

**Comment by drieschel** [comment]
Now it seems to compile, yeah! Thank you Kerber! :)

**Comment by surkovalex** [comment]
Sorry guys, I do not always have the time to check everything.

**Comment by drieschel** [comment]
Kerber, I really would like to faciliate your work. But my project related knowledge is too small (and probably my c related knowledge too). Anyway I am willing to learn. You can give me some simple excercises for better understanding.
