### ISSUE TITLE
RPI2 issues with hdhome run in 6.0.0

### ISSUE THREAD

**Issue by JustMev** [surkovalex/OpenELEC.tv#25]
make[3]: Leaving directory '/home/justme/30octobersurkoOpenELEC.tv/build.OpenELEC-RPi2.arm-6.0.0/dvbhdhomerun-20130704/.armv7ve-openelec-linux-gnueabi'
CMakeFiles/Makefile2:99: recipe for target 'CMakeFiles/userhdhomerun.dir/all' failed
make[2]: *** [CMakeFiles/userhdhomerun.dir/all] Error 2
make[2]: Leaving directory '/home/justme/30octobersurkoOpenELEC.tv/build.OpenELEC-RPi2.arm-6.0.0/dvbhdhomerun-20130704/.armv7ve-openelec-linux-gnueabi'
Makefile:127: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/justme/30octobersurkoOpenELEC.tv/build.OpenELEC-RPi2.arm-6.0.0/dvbhdhomerun-20130704/.armv7ve-openelec-linux-gnueabi'
make: *** [image] Error 2

**Comment by surkovalex** [comment]
Sorry, i don't use any RPi devices, maybe merge bugs.
