### ISSUE TITLE
Branch 6.0 M8S

### ISSUE THREAD

**Issue by JustMev** [surkovalex/OpenELEC.tv#32]
SYSMAP  System.map
OBJCOPY arch/arm/boot/ccImage
Kernel: arch/arm/boot/ccImage is ready
/bin/sh: lzop: command not found
/home/Fred/OpenELEC.tv/build.OpenELEC-Amlogic.arm-M8S-/linux-amlogic-3.10-e6dedd5/arch/arm/boot/Makefile:122: recipe for target 'arch/arm/boot/ccImage.lzo' fa                            iled
make[1]: *** [arch/arm/boot/ccImage.lzo] Error 127
/home/Fred/OpenELEC.tv/build.OpenELEC-Amlogic.arm-M8S-/linux-amlogic-3.10-e6dedd5/arch/arm/Makefile:306: recipe for target 'uImage' failed
make: *** [uImage] Error 2

**Comment by alexandersurkov** [comment]
> /bin/sh: lzop: command not found

sudo apt-get install lzop

**Comment by JustMev** [comment]
thank you sir
