### ISSUE TITLE
OpenELEC 6-0 -  Missing squashfs

### ISSUE THREAD

**Issue by JustMev** [surkovalex/OpenELEC.tv#34]
GET      squashfs
--2016-03-05 21:47:05--  http://prdownloads.sourceforge.net/squashfs/squashfs/squashfs4.3/squashfs4.3.tar.gz
Resolving prdownloads.sourceforge.net (prdownloads.sourceforge.net)... 216.34.181.59
Connecting to prdownloads.sourceforge.net (prdownloads.sourceforge.net)|216.34.181.59|:80... connected.
HTTP request sent, awaiting response... 302 Found
Location: http://iweb.dl.sourceforge.net/project/squashfs/squashfs/squashfs4.3/squashfs4.3.tar.gz [following]
--2016-03-05 21:47:05--  http://iweb.dl.sourceforge.net/project/squashfs/squashfs/squashfs4.3/squashfs4.3.tar.gz
Resolving iweb.dl.sourceforge.net (iweb.dl.sourceforge.net)... 70.38.0.134, 2607:f748:10:12::5f:2
Connecting to iweb.dl.sourceforge.net (iweb.dl.sourceforge.net)|70.38.0.134|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 182550 (178K) [application/x-gzip]
Saving to: 'sources/squashfs/squashfs4.3.tar.gz'

100%[===================================================================================================================================================>] 182,550     --.-K/s   in 0.1s

2016-03-05 21:47:05 (1.66 MB/s) - 'sources/squashfs/squashfs4.3.tar.gz' saved [182550/182550]

  UNPACK   squashfs
mv: target '6.0.1/squashfs-4.3' is not a directory

**Comment by alexandersurkov** [comment]
possible problems on the sourceforge.net
try to remove sources/squashfs and try again.
Resolution of this problem is not in my competence
