### ISSUE TITLE
Any way to make work on S805 (Minix Neo X6) ?

### ISSUE THREAD

**Issue by artouiros** [surkovalex/OpenELEC.tv#35]
Hi, is it any way to make it work on Minix Neo X6? The system is booting, but there is no HDMI output.

**Comment by alexandersurkov** [comment]
Уже отписывался на форуме
http://xbmc.ru/forum/showpost.php?p=91471&postcount=2219

**Comment by surkovalex** [comment]
Уже отписывался на форуме http://xbmc.ru/forum/showpost.php?p=91471&postcount=2219
