### ISSUE TITLE
OpenELEC-6.0 - M8S

### ISSUE THREAD

**Issue by JustMev** [surkovalex/OpenELEC.tv#36]
DTC: command not found
Me@OpenELEC:~/OpenELEC.tv$ rm  /home/Me/OpenELEC.tv/build.OpenELEC-Amlogic.arm-M8S-6.0.3/linux-amlogic-3.10-b54bef2/arch/arm/boot/dts/amlogic/meson8m2_n200C_2G.dts

rm: cannot remove `/home/Me/OpenELEC.tv/build.OpenELEC-Amlogic.arm-M8S-6.0.3/linux-amlogic-3.10-b54bef2/arch/arm/boot/dts/amlogic/meson8m2_n200C_2G.dts': No such file or directory

Me@OpenELEC:~/OpenELEC.tv$ /home/Me/OpenELEC.tv/packages/linux/package.mk: line 153: /home/Just/OpenELEC.tv/projects/Amlogic/dtbTool: No such file or directory

bash: /home/Me/OpenELEC.tv/packages/linux/package.mk:: No such file or directory

**Comment by surkovalex** [comment]
Try - apt-get install device-tree-compiler

**Comment by JustMev** [comment]
nope same issues

**Comment by JustMev** [comment]
solved
